apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diazoxide-symfony.fullname" . }}
  labels:
    {{- include "diazoxide-symfony.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "diazoxide-symfony.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "diazoxide-symfony.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diazoxide-symfony.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frankenphp
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frankenphp.image.repository }}:{{ .Values.frankenphp.image.tag }}"
          imagePullPolicy: {{ .Values.frankenphp.image.pullPolicy }}
          env:
            - name: SERVER_NAME
              value: ":80"
            - name: CADDY_EXTRA_CONFIG
              value: |
                  :2019 {
                     metrics
                  }
            {{- include "diazoxide-symfony.env" . | nindent 12 }}
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: metrics
            containerPort: 2019
            protocol: TCP
          volumeMounts:
            - mountPath: /var/run/php
              name: php-socket
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
          startupProbe:
            {{- toYaml .Values.frankenphp.startupProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frankenphp.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.frankenphp.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.frankenphp.messenger.enabled }}
        - name: {{ .Chart.Name }}-consumer
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frankenphp.image.repository }}:{{ .Values.frankenphp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frankenphp.image.pullPolicy }}
          args: ['bin/console', 'messenger:consume']
          env:
            {{- include "diazoxide-symfony.env" . | nindent 12 }}
          startupProbe:
            exec:
              command: ['pgrep', '-f', 'php bin/console messenger:consume']
            failureThreshold: 40
            periodSeconds: 3
          readinessProbe:
            exec:
              command: ['pgrep', '-f', 'php bin/console messenger:consume']
            periodSeconds: 3
          livenessProbe:
            exec:
              command: ['pgrep', '-f', 'php bin/console messenger:consume']
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}  
      volumes:
      - name: php-socket
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
